/**
 * ATMOS MARKET — Runtime Config
 * public/config.js
 *
 * In production this file is auto-generated by Vercel
 * from environment variables (see vercel.json rewrites).
 *
 * For local development: edit these values directly.
 * Never commit real keys — use .env.local instead and
 * let the build script regenerate this file.
 */
window.ATMOS_CONFIG = {
  // Supabase (get from supabase.com → project → Settings → API)
  SUPABASE_URL:    'https://YOUR_PROJECT.supabase.co',
  SUPABASE_ANON:   'YOUR_ANON_PUBLIC_KEY',

  // Push server (Railway/Render URL after deploying server/)
  PUSH_SERVER_URL: '',

  // VAPID public key (generated once, same value in server .env)
  VAPID_PUBLIC_KEY: 'BAiPyrblH1Gcdf3evvZfMMBAA__dhFKtKJpvAdxTz-5_fSC61MUXc5e_KnmqV4C-kE_wzGGbzI3zFJI-s7SMn0Q',

  // CORS proxy for Kalshi API in browser
  // In React Native app this is set to '' (direct calls)
  CORS_PROXY: 'https://corsproxy.io/?',
};
